Lecture 08: 

Today's Lecture introduces Pandas (Python Data Analysis Library). Although you will not need to use it in todays lab it is a commonly used library that you should have some familiarity with, and maybe use in your projects!

Numpy provides basic functionalities with multidimensional array structure built with homogeneous data. Pandas provides a lot of data manipulation functionalities on top of numpy using structures called DataFrames and Series. 

When would you use Pandas?
If you just need to read in a dataset before you use it, you can use numpy. If you need to do any amount of preprocessing with your data, pandas should be your go-to

Advantages of Pandas:
- Deals with missing values well (can still sort, fill in values, perform element-wise operations) without breaking. Missing values is a common issue when working with large datasets
- Very flexible: Easy to add columns/ rows, or combine dataframes together 
- Supports different types of data (doesn't need to be homogeneous)
- Good IO Capabilities
- Many high level data manipulation functionalities that don't exist or are much more inconvenient in numpy. 


Useful Cheatsheet:
https://s3.amazonaws.com/assets.datacamp.com/blog_assets/PandasPythonForDataScience.pdf

In [1]:
import numpy as np
import pandas as pd

First Data Structure: Series 
- 1-D labelled array holding any data type

In [2]:
s1 = pd.Series([2,5,1,4])
s2 = pd.Series([2,5,1,4], index = ['a','b','c','d'])

In [3]:
print(s1)
print("modified indexing")
print(s2)

0    2
1    5
2    1
3    4
dtype: int64
modified indexing
a    2
b    5
c    1
d    4
dtype: int64

Second Data Structure: DataFrames
- Think of it as a 2D analogue of series
- Similar to 2D numpy arrays with a number of functional advantages

Method 1: Creating data frame directly

In [4]:
# Data can be a numpy array or dictionary
# Can then create the dataframe using the data and with column order of your choosing
data = {'Code': ['Phys61',  'Phys63',  'Phys65'], 'Professor': ['Pat', 'Blas', 'Hari'], 'Course': ['Special Relativity',  'Electricity and Magnetism',  'Modern Physics']
}
df1 = pd.DataFrame(data, columns = ['Code', 'Course', 'Professor'])

In [5]:
df1

     Code                     Course Professor
0  Phys61         Special Relativity       Pat
1  Phys63  Electricity and Magnetism      Blas
2  Phys65             Modern Physics      Hari

In [6]:
# Can check for types
df1.dtypes

Code         object
Course       object
Professor    object
dtype: object

METHOD 2: Reading a data file into a data frame
- Accomodates more than just csv files, can also read in multiple sheets from Excel 
- Very powerful I/O capabilities

In [8]:
sales_df = pd.read_csv('sample_data.csv', header=0)

In [9]:
sales_df

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,255.28,159.42,2533654.00,1582243.50,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50
5,Australia and Oceania,Solomon Islands,Baby Food,Online,C,2/4/2015,547995746,2/21/2015,2974,255.28,159.42,759202.72,474115.08,285087.64
6,Sub-Saharan Africa,Angola,Household,Offline,M,4/23/2011,135425221,4/27/2011,4187,668.27,502.54,2798046.49,2104134.98,693911.51
7,Sub-Saharan Africa,Burkina Faso,Vegetables,Online,H,7/17/2012,871543967,7/27/2012,8082,154.06,90.93,1245112.92,734896.26,510216.66
8,Sub-Saharan Africa,Republic of the Congo,Personal Care,Offline,M,7/14/2015,770463311,8/25/2015,6070,81.73,56.67,496101.10,343986.90,152114.20
9,Sub-Saharan Africa,Senegal,Cereal,Online,H,4/18/2014,616607081,5/30/2014,6593,205.70,117.11,1356180.10,772106.23,584073.87
10,Asia,Kyrgyzstan,Vegetables,Online,H,6/24/2011,814711606,7/12/2011,124,154.06,90.93,19103.44,11275.32,7828.12
11,Sub-Saharan Africa,Cape Verde,Clothes,Offline,H,8/2/2014,939825713,8/19/2014,4168,109.28,35.84,455479.04,149381.12,306097.92
12,Asia,Bangladesh,Clothes,Online,L,1/13/2017,187310731,3/1/2017,8263,109.28,35.84,902980.64,296145.92,606834.72
13,Central America and the Caribbean,Honduras,Household,Offline,H,2/8/2017,522840487,2/13/2017,8974,668.27,502.54,5997054.98,4509793.96,1487261.02
14,Asia,Mongolia,Personal Care,Offline,C,2/19/2014,832401311,2/23/2014,4901,81.73,56.67,400558.73,277739.67,122819.06
15,Europe,Bulgaria,Clothes,Online,M,4/23/2012,972292029,6/3/2012,1673,109.28,35.84,182825.44,59960.32,122865.12
16,Asia,Sri Lanka,Cosmetics,Offline,M,11/19/2016,419123971,12/18/2016,6952,437.20,263.33,3039414.40,1830670.16,1208744.24
17,Sub-Saharan Africa,Cameroon,Beverages,Offline,C,4/1/2015,519820964,4/18/2015,5430,47.45,31.79,257653.50,172619.70,85033.80
18,Asia,Turkmenistan,Household,Offline,L,12/30/2010,441619336,1/20/2011,3830,668.27,502.54,2559474.10,1924728.20,634745.90
19,Australia and Oceania,East Timor,Meat,Online,L,7/31/2012,322067916,9/11/2012,5908,421.89,364.69,2492526.12,2154588.52,337937.60
20,Europe,Norway,Baby Food,Online,L,5/14/2014,819028031,6/28/2014,7450,255.28,159.42,1901836.00,1187679.00,714157.00
21,Europe,Portugal,Baby Food,Online,H,7/31/2015,860673511,9/3/2015,1273,255.28,159.42,324971.44,202941.66,122029.78
22,Central America and the Caribbean,Honduras,Snacks,Online,L,6/30/2016,795490682,7/26/2016,2225,152.58,97.44,339490.50,216804.00,122686.50
23,Australia and Oceania,New Zealand,Fruits,Online,H,9/8/2014,142278373,10/4/2014,2187,9.33,6.92,20404.71,15134.04,5270.67
24,Europe,Moldova,Personal Care,Online,L,5/7/2016,740147912,5/10/2016,5070,81.73,56.67,414371.10,287316.90,127054.20
25,Europe,France,Cosmetics,Online,H,5/22/2017,898523128,6/5/2017,1815,437.20,263.33,793518.00,477943.95,315574.05
26,Australia and Oceania,Kiribati,Fruits,Online,M,10/13/2014,347140347,11/10/2014,5398,9.33,6.92,50363.34,37354.16,13009.18
27,Sub-Saharan Africa,Mali,Fruits,Online,L,5/7/2010,686048400,5/10/2010,5822,9.33,6.92,54319.26,40288.24,14031.02
28,Europe,Norway,Beverages,Offline,C,7/18/2014,435608613,7/30/2014,5124,47.45,31.79,243133.80,162891.96,80241.84
29,Sub-Saharan Africa,The Gambia,Household,Offline,L,5/26/2012,886494815,6/9/2012,2370,668.27,502.54,1583799.90,1191019.80,392780.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,Asia,Turkmenistan,Office Supplies,Online,M,4/23/2013,462405812,5/20/2013,5010,651.21,524.96,3262562.10,2630049.60,632512.50
71,Middle East and North Africa,Libya,Fruits,Online,L,8/14/2015,816200339,9/30/2015,673,9.33,6.92,6279.09,4657.16,1621.93
72,Sub-Saharan Africa,Democratic Republic of the Congo,Beverages,Online,C,5/26/2011,585920464,7/15/2011,5741,47.45,31.79,272410.45,182506.39,89904.06
73,Sub-Saharan Africa,Djibouti,Cereal,Online,H,5/20/2017,555990016,6/17/2017,8656,205.70,117.11,1780539.20,1013704.16,766835.04
74,Middle East and North Africa,Pakistan,Cosmetics,Offline,L,7/5/2013,231145322,8/16/2013,9892,437.20,263.33,4324782.40,2604860.36,1719922.04
75,North America,Mexico,Household,Offline,C,11/6/2014,986435210,12/12/2014,6954,668.27,502.54,4647149.58,3494663.16,1152486.42
76,Australia and Oceania,Federated States of Micronesia,Beverages,Online,C,10/28/2014,217221009,11/15/2014,9379,47.45,31.79,445033.55,298158.41,146875.14
77,Asia,Laos,Vegetables,Offline,C,9/15/2011,789176547,10/23/2011,3732,154.06,90.93,574951.92,339350.76,235601.16
78,Europe,Monaco,Baby Food,Offline,H,5/29/2012,688288152,6/2/2012,8614,255.28,159.42,2198981.92,1373243.88,825738.04
79,Australia and Oceania,Samoa,Cosmetics,Online,H,7/20/2013,670854651,8/7/2013,9654,437.20,263.33,4220728.80,2542187.82,1678540.98
80,Europe,Spain,Household,Offline,L,10/21/2012,213487374,11/30/2012,4513,668.27,502.54,3015902.51,2267963.02,747939.49
81,Middle East and North Africa,Lebanon,Clothes,Online,L,9/18/2012,663110148,10/8/2012,7884,109.28,35.84,861563.52,282562.56,579000.96
82,Middle East and North Africa,Iran,Cosmetics,Online,H,11/15/2016,286959302,12/8/2016,6489,437.20,263.33,2836990.80,1708748.37,1128242.43
83,Sub-Saharan Africa,Zambia,Snacks,Online,L,1/4/2011,122583663,1/5/2011,4085,152.58,97.44,623289.30,398042.40,225246.90
84,Sub-Saharan Africa,Kenya,Vegetables,Online,L,3/18/2012,827844560,4/7/2012,6457,154.06,90.93,994765.42,587135.01,407630.41
85,North America,Mexico,Personal Care,Offline,L,2/17/2012,430915820,3/20/2012,6422,81.73,56.67,524870.06,363934.74,160935.32
86,Sub-Saharan Africa,Sao Tome and Principe,Beverages,Offline,C,1/16/2011,180283772,1/21/2011,8829,47.45,31.79,418936.05,280673.91,138262.14
87,Sub-Saharan Africa,The Gambia,Baby Food,Offline,M,2/3/2014,494747245,3/20/2014,5559,255.28,159.42,1419101.52,886215.78,532885.74
88,Middle East and North Africa,Kuwait,Fruits,Online,M,4/30/2012,513417565,5/18/2012,522,9.33,6.92,4870.26,3612.24,1258.02
89,Europe,Slovenia,Beverages,Offline,C,10/23/2016,345718562,11/25/2016,4660,47.45,31.79,221117.00,148141.40,72975.60
90,Sub-Saharan Africa,Sierra Leone,Office Supplies,Offline,H,12/6/2016,621386563,12/14/2016,948,651.21,524.96,617347.08,497662.08,119685.00
91,Australia and Oceania,Australia,Beverages,Offline,H,7/7/2014,240470397,7/11/2014,9389,47.45,31.79,445508.05,298476.31,147031.74
92,Middle East and North Africa,Azerbaijan,Office Supplies,Online,M,6/13/2012,423331391,7/24/2012,2021,651.21,524.96,1316095.41,1060944.16,255151.25
93,Europe,Romania,Cosmetics,Online,H,11/26/2010,660643374,12/25/2010,7910,437.20,263.33,3458252.00,2082940.30,1375311.70
94,Central America and the Caribbean,Nicaragua,Beverages,Offline,C,2/8/2011,963392674,3/21/2011,8156,47.45,31.79,387002.20,259279.24,127722.96
95,Sub-Saharan Africa,Mali,Clothes,Online,M,7/26/2011,512878119,9/3/2011,888,109.28,35.84,97040.64,31825.92,65214.72
96,Asia,Malaysia,Fruits,Offline,L,11/11/2011,810711038,12/28/2011,6267,9.33,6.92,58471.11,43367.64,15103.47
97,Sub-Saharan Africa,Sierra Leone,Vegetables,Offline,C,6/1/2016,728815257,6/29/2016,1485,154.06,90.93,228779.10,135031.05,93748.05
98,North America,Mexico,Personal Care,Offline,M,7/30/2015,559427106,8/8/2015,5767,81.73,56.67,471336.91,326815.89,144521.02
99,Sub-Saharan Africa,Mozambique,Household,Offline,L,2/10/2012,665095412,2/15/2012,5367,668.27,502.54,3586605.09,2697132.18,889472.91

In [10]:
# Pick out a column
sales_df['Item Type']

0           Baby Food
1              Cereal
2     Office Supplies
3              Fruits
4     Office Supplies
5           Baby Food
6           Household
7          Vegetables
8       Personal Care
9              Cereal
10         Vegetables
11            Clothes
12            Clothes
13          Household
14      Personal Care
15            Clothes
16          Cosmetics
17          Beverages
18          Household
19               Meat
20          Baby Food
21          Baby Food
22             Snacks
23             Fruits
24      Personal Care
25          Cosmetics
26             Fruits
27             Fruits
28          Beverages
29          Household
           ...
70    Office Supplies
71             Fruits
72          Beverages
73             Cereal
74          Cosmetics
75          Household
76          Beverages
77         Vegetables
78          Baby Food
79          Cosmetics
80          Household
81            Clothes
82          Cosmetics
83             Snacks
84         Vegetables
85      Personal Care
86          Beverages
87          Baby Food
88             Fruits
89          Beverages
90    Office Supplies
91          Beverages
92    Office Supplies
93          Cosmetics
94          Beverages
95            Clothes
96             Fruits
97         Vegetables
98      Personal Care
99          Household
Name: Item Type, Length: 100, dtype: object

In [11]:
# Can pick out multiple columns with a list
sales_df[["Region", "Units Sold"]]

                               Region  Units Sold
0               Australia and Oceania        9925
1   Central America and the Caribbean        2804
2                              Europe        1779
3                  Sub-Saharan Africa        8102
4                  Sub-Saharan Africa        5062
5               Australia and Oceania        2974
6                  Sub-Saharan Africa        4187
7                  Sub-Saharan Africa        8082
8                  Sub-Saharan Africa        6070
9                  Sub-Saharan Africa        6593
10                               Asia         124
11                 Sub-Saharan Africa        4168
12                               Asia        8263
13  Central America and the Caribbean        8974
14                               Asia        4901
15                             Europe        1673
16                               Asia        6952
17                 Sub-Saharan Africa        5430
18                               Asia        3830
19              Australia and Oceania        5908
20                             Europe        7450
21                             Europe        1273
22  Central America and the Caribbean        2225
23              Australia and Oceania        2187
24                             Europe        5070
25                             Europe        1815
26              Australia and Oceania        5398
27                 Sub-Saharan Africa        5822
28                             Europe        5124
29                 Sub-Saharan Africa        2370
..                                ...         ...
70                               Asia        5010
71       Middle East and North Africa         673
72                 Sub-Saharan Africa        5741
73                 Sub-Saharan Africa        8656
74       Middle East and North Africa        9892
75                      North America        6954
76              Australia and Oceania        9379
77                               Asia        3732
78                             Europe        8614
79              Australia and Oceania        9654
80                             Europe        4513
81       Middle East and North Africa        7884
82       Middle East and North Africa        6489
83                 Sub-Saharan Africa        4085
84                 Sub-Saharan Africa        6457
85                      North America        6422
86                 Sub-Saharan Africa        8829
87                 Sub-Saharan Africa        5559
88       Middle East and North Africa         522
89                             Europe        4660
90                 Sub-Saharan Africa         948
91              Australia and Oceania        9389
92       Middle East and North Africa        2021
93                             Europe        7910
94  Central America and the Caribbean        8156
95                 Sub-Saharan Africa         888
96                               Asia        6267
97                 Sub-Saharan Africa        1485
98                      North America        5767
99                 Sub-Saharan Africa        5367

[100 rows x 2 columns]

In [12]:
# Supports index slicing as well 
sales_df[1:5]

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50

DATA SELECTION METHODS
1. iloc is location/index based
2. loc is label based
3. ix is like loc but default to iloc when no label is specified. Kind of like combination of both

In [20]:
# Parameters can be list, value, or slice of columns / rows. 

print("Example 1: By Index")
print(sales_df.iloc[0:5,[1,3,5]])
print("Example 2: By Label")
print(sales_df.loc[sales_df['Region'] == "Asia", "Item Type"])
print("Example 3: By Label")
print(sales_df.loc[(sales_df["Unit Cost"] < 10.0) | (sales_df["Unit Cost"] > 600.0), sales_df.columns])

Example 1: By Index
                 Country Sales Channel Order Date
0                 Tuvalu       Offline  5/28/2010
1                Grenada        Online  8/22/2012
2                 Russia       Offline   5/2/2014
3  Sao Tome and Principe        Online  6/20/2014
4                 Rwanda       Offline   2/1/2013
Example 2: By Label
10         Vegetables
12            Clothes
14      Personal Care
16          Cosmetics
18          Household
33          Household
38    Office Supplies
44            Clothes
70    Office Supplies
77         Vegetables
96             Fruits
Name: Item Type, dtype: object
Example 3: By Label
                          Region                Country Item Type  \
3             Sub-Saharan Africa  Sao Tome and Principe    Fruits
23         Australia and Oceania            New Zealand    Fruits
26         Australia and Oceania               Kiribati    Fruits
27            Sub-Saharan Africa                   Mali    Fruits
36  Middle East and North Africa                  Syria    Fruits
51            Sub-Saharan Africa                Lesotho    Fruits
54            Sub-Saharan Africa  Sao Tome and Principe    Fruits
71  Middle East and North Africa                  Libya    Fruits
88  Middle East and North Africa                 Kuwait    Fruits
96                          Asia               Malaysia    Fruits

   Sales Channel Order Priority  Order Date   Order ID   Ship Date  \
3         Online              C   6/20/2014  514321792    7/5/2014
23        Online              H    9/8/2014  142278373   10/4/2014
26        Online              M  10/13/2014  347140347  11/10/2014
27        Online              L    5/7/2010  686048400   5/10/2010
36        Online              L  11/22/2011  162052476   12/3/2011
51        Online              L   8/18/2013  918419539   9/18/2013
54       Offline              H   9/17/2013  508980977  10/24/2013
71        Online              L   8/14/2015  816200339   9/30/2015
88        Online              M   4/30/2012  513417565   5/18/2012
96       Offline              L  11/11/2011  810711038  12/28/2011

    Units Sold  Unit Price  Unit Cost  Total Revenue  Total Cost  Total Profit
3         8102        9.33       6.92       75591.66    56065.84      19525.82
23        2187        9.33       6.92       20404.71    15134.04       5270.67
26        5398        9.33       6.92       50363.34    37354.16      13009.18
27        5822        9.33       6.92       54319.26    40288.24      14031.02
36        3784        9.33       6.92       35304.72    26185.28       9119.44
51        9606        9.33       6.92       89623.98    66473.52      23150.46
54        7637        9.33       6.92       71253.21    52848.04      18405.17
71         673        9.33       6.92        6279.09     4657.16       1621.93
88         522        9.33       6.92        4870.26     3612.24       1258.02
96        6267        9.33       6.92       58471.11    43367.64      15103.47

SORTING METHODS: sort_index, sort_values

In [23]:
# Sorts by column names (alphabetically)
sales_df.sort_index(1)

,Country,Item Type,Order Date,Order ID,Order Priority,Region,Sales Channel,Ship Date,Total Cost,Total Profit,Total Revenue,Unit Cost,Unit Price,Units Sold
0,Tuvalu,Baby Food,5/28/2010,669165933,H,Australia and Oceania,Offline,6/27/2010,1582243.50,951410.50,2533654.00,159.42,255.28,9925
1,Grenada,Cereal,8/22/2012,963881480,C,Central America and the Caribbean,Online,9/15/2012,328376.44,248406.36,576782.80,117.11,205.70,2804
2,Russia,Office Supplies,5/2/2014,341417157,L,Europe,Offline,5/8/2014,933903.84,224598.75,1158502.59,524.96,651.21,1779
3,Sao Tome and Principe,Fruits,6/20/2014,514321792,C,Sub-Saharan Africa,Online,7/5/2014,56065.84,19525.82,75591.66,6.92,9.33,8102
4,Rwanda,Office Supplies,2/1/2013,115456712,L,Sub-Saharan Africa,Offline,2/6/2013,2657347.52,639077.50,3296425.02,524.96,651.21,5062
5,Solomon Islands,Baby Food,2/4/2015,547995746,C,Australia and Oceania,Online,2/21/2015,474115.08,285087.64,759202.72,159.42,255.28,2974
6,Angola,Household,4/23/2011,135425221,M,Sub-Saharan Africa,Offline,4/27/2011,2104134.98,693911.51,2798046.49,502.54,668.27,4187
7,Burkina Faso,Vegetables,7/17/2012,871543967,H,Sub-Saharan Africa,Online,7/27/2012,734896.26,510216.66,1245112.92,90.93,154.06,8082
8,Republic of the Congo,Personal Care,7/14/2015,770463311,M,Sub-Saharan Africa,Offline,8/25/2015,343986.90,152114.20,496101.10,56.67,81.73,6070
9,Senegal,Cereal,4/18/2014,616607081,H,Sub-Saharan Africa,Online,5/30/2014,772106.23,584073.87,1356180.10,117.11,205.70,6593
10,Kyrgyzstan,Vegetables,6/24/2011,814711606,H,Asia,Online,7/12/2011,11275.32,7828.12,19103.44,90.93,154.06,124
11,Cape Verde,Clothes,8/2/2014,939825713,H,Sub-Saharan Africa,Offline,8/19/2014,149381.12,306097.92,455479.04,35.84,109.28,4168
12,Bangladesh,Clothes,1/13/2017,187310731,L,Asia,Online,3/1/2017,296145.92,606834.72,902980.64,35.84,109.28,8263
13,Honduras,Household,2/8/2017,522840487,H,Central America and the Caribbean,Offline,2/13/2017,4509793.96,1487261.02,5997054.98,502.54,668.27,8974
14,Mongolia,Personal Care,2/19/2014,832401311,C,Asia,Offline,2/23/2014,277739.67,122819.06,400558.73,56.67,81.73,4901
15,Bulgaria,Clothes,4/23/2012,972292029,M,Europe,Online,6/3/2012,59960.32,122865.12,182825.44,35.84,109.28,1673
16,Sri Lanka,Cosmetics,11/19/2016,419123971,M,Asia,Offline,12/18/2016,1830670.16,1208744.24,3039414.40,263.33,437.20,6952
17,Cameroon,Beverages,4/1/2015,519820964,C,Sub-Saharan Africa,Offline,4/18/2015,172619.70,85033.80,257653.50,31.79,47.45,5430
18,Turkmenistan,Household,12/30/2010,441619336,L,Asia,Offline,1/20/2011,1924728.20,634745.90,2559474.10,502.54,668.27,3830
19,East Timor,Meat,7/31/2012,322067916,L,Australia and Oceania,Online,9/11/2012,2154588.52,337937.60,2492526.12,364.69,421.89,5908
20,Norway,Baby Food,5/14/2014,819028031,L,Europe,Online,6/28/2014,1187679.00,714157.00,1901836.00,159.42,255.28,7450
21,Portugal,Baby Food,7/31/2015,860673511,H,Europe,Online,9/3/2015,202941.66,122029.78,324971.44,159.42,255.28,1273
22,Honduras,Snacks,6/30/2016,795490682,L,Central America and the Caribbean,Online,7/26/2016,216804.00,122686.50,339490.50,97.44,152.58,2225
23,New Zealand,Fruits,9/8/2014,142278373,H,Australia and Oceania,Online,10/4/2014,15134.04,5270.67,20404.71,6.92,9.33,2187
24,Moldova,Personal Care,5/7/2016,740147912,L,Europe,Online,5/10/2016,287316.90,127054.20,414371.10,56.67,81.73,5070
25,France,Cosmetics,5/22/2017,898523128,H,Europe,Online,6/5/2017,477943.95,315574.05,793518.00,263.33,437.20,1815
26,Kiribati,Fruits,10/13/2014,347140347,M,Australia and Oceania,Online,11/10/2014,37354.16,13009.18,50363.34,6.92,9.33,5398
27,Mali,Fruits,5/7/2010,686048400,L,Sub-Saharan Africa,Online,5/10/2010,40288.24,14031.02,54319.26,6.92,9.33,5822
28,Norway,Beverages,7/18/2014,435608613,C,Europe,Offline,7/30/2014,162891.96,80241.84,243133.80,31.79,47.45,5124
29,The Gambia,Household,5/26/2012,886494815,L,Sub-Saharan Africa,Offline,6/9/2012,1191019.80,392780.10,1583799.90,502.54,668.27,2370
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,Turkmenistan,Office Supplies,4/23/2013,462405812,M,Asia,Online,5/20/2013,2630049.60,632512.50,3262562.10,524.96,651.21,5010
71,Libya,Fruits,8/14/2015,816200339,L,Middle East and North Africa,Online,9/30/2015,4657.16,1621.93,6279.09,6.92,9.33,673
72,Democratic Republic of the Congo,Beverages,5/26/2011,585920464,C,Sub-Saharan Africa,Online,7/15/2011,182506.39,89904.06,272410.45,31.79,47.45,5741
73,Djibouti,Cereal,5/20/2017,555990016,H,Sub-Saharan Africa,Online,6/17/2017,1013704.16,766835.04,1780539.20,117.11,205.70,8656
74,Pakistan,Cosmetics,7/5/2013,231145322,L,Middle East and North Africa,Offline,8/16/2013,2604860.36,1719922.04,4324782.40,263.33,437.20,9892
75,Mexico,Household,11/6/2014,986435210,C,North America,Offline,12/12/2014,3494663.16,1152486.42,4647149.58,502.54,668.27,6954
76,Federated States of Micronesia,Beverages,10/28/2014,217221009,C,Australia and Oceania,Online,11/15/2014,298158.41,146875.14,445033.55,31.79,47.45,9379
77,Laos,Vegetables,9/15/2011,789176547,C,Asia,Offline,10/23/2011,339350.76,235601.16,574951.92,90.93,154.06,3732
78,Monaco,Baby Food,5/29/2012,688288152,H,Europe,Offline,6/2/2012,1373243.88,825738.04,2198981.92,159.42,255.28,8614
79,Samoa,Cosmetics,7/20/2013,670854651,H,Australia and Oceania,Online,8/7/2013,2542187.82,1678540.98,4220728.80,263.33,437.20,9654
80,Spain,Household,10/21/2012,213487374,L,Europe,Offline,11/30/2012,2267963.02,747939.49,3015902.51,502.54,668.27,4513
81,Lebanon,Clothes,9/18/2012,663110148,L,Middle East and North Africa,Online,10/8/2012,282562.56,579000.96,861563.52,35.84,109.28,7884
82,Iran,Cosmetics,11/15/2016,286959302,H,Middle East and North Africa,Online,12/8/2016,1708748.37,1128242.43,2836990.80,263.33,437.20,6489
83,Zambia,Snacks,1/4/2011,122583663,L,Sub-Saharan Africa,Online,1/5/2011,398042.40,225246.90,623289.30,97.44,152.58,4085
84,Kenya,Vegetables,3/18/2012,827844560,L,Sub-Saharan Africa,Online,4/7/2012,587135.01,407630.41,994765.42,90.93,154.06,6457
85,Mexico,Personal Care,2/17/2012,430915820,L,North America,Offline,3/20/2012,363934.74,160935.32,524870.06,56.67,81.73,6422
86,Sao Tome and Principe,Beverages,1/16/2011,180283772,C,Sub-Saharan Africa,Offline,1/21/2011,280673.91,138262.14,418936.05,31.79,47.45,8829
87,The Gambia,Baby Food,2/3/2014,494747245,M,Sub-Saharan Africa,Offline,3/20/2014,886215.78,532885.74,1419101.52,159.42,255.28,5559
88,Kuwait,Fruits,4/30/2012,513417565,M,Middle East and North Africa,Online,5/18/2012,3612.24,1258.02,4870.26,6.92,9.33,522
89,Slovenia,Beverages,10/23/2016,345718562,C,Europe,Offline,11/25/2016,148141.40,72975.60,221117.00,31.79,47.45,4660
90,Sierra Leone,Office Supplies,12/6/2016,621386563,H,Sub-Saharan Africa,Offline,12/14/2016,497662.08,119685.00,617347.08,524.96,651.21,948
91,Australia,Beverages,7/7/2014,240470397,H,Australia and Oceania,Offline,7/11/2014,298476.31,147031.74,445508.05,31.79,47.45,9389
92,Azerbaijan,Office Supplies,6/13/2012,423331391,M,Middle East and North Africa,Online,7/24/2012,1060944.16,255151.25,1316095.41,524.96,651.21,2021
93,Romania,Cosmetics,11/26/2010,660643374,H,Europe,Online,12/25/2010,2082940.30,1375311.70,3458252.00,263.33,437.20,7910
94,Nicaragua,Beverages,2/8/2011,963392674,C,Central America and the Caribbean,Offline,3/21/2011,259279.24,127722.96,387002.20,31.79,47.45,8156
95,Mali,Clothes,7/26/2011,512878119,M,Sub-Saharan Africa,Online,9/3/2011,31825.92,65214.72,97040.64,35.84,109.28,888
96,Malaysia,Fruits,11/11/2011,810711038,L,Asia,Offline,12/28/2011,43367.64,15103.47,58471.11,6.92,9.33,6267
97,Sierra Leone,Vegetables,6/1/2016,728815257,C,Sub-Saharan Africa,Offline,6/29/2016,135031.05,93748.05,228779.10,90.93,154.06,1485
98,Mexico,Personal Care,7/30/2015,559427106,M,North America,Offline,8/8/2015,326815.89,144521.02,471336.91,56.67,81.73,5767
99,Mozambique,Household,2/10/2012,665095412,L,Sub-Saharan Africa,Offline,2/15/2012,2697132.18,889472.91,3586605.09,502.54,668.27,5367

In [24]:
# Sort by unit cost
sales_df.sort_values("Unit Cost")

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
54,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Offline,H,9/17/2013,508980977,10/24/2013,7637,9.33,6.92,71253.21,52848.04,18405.17
51,Sub-Saharan Africa,Lesotho,Fruits,Online,L,8/18/2013,918419539,9/18/2013,9606,9.33,6.92,89623.98,66473.52,23150.46
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,7/5/2014,8102,9.33,6.92,75591.66,56065.84,19525.82
96,Asia,Malaysia,Fruits,Offline,L,11/11/2011,810711038,12/28/2011,6267,9.33,6.92,58471.11,43367.64,15103.47
36,Middle East and North Africa,Syria,Fruits,Online,L,11/22/2011,162052476,12/3/2011,3784,9.33,6.92,35304.72,26185.28,9119.44
88,Middle East and North Africa,Kuwait,Fruits,Online,M,4/30/2012,513417565,5/18/2012,522,9.33,6.92,4870.26,3612.24,1258.02
27,Sub-Saharan Africa,Mali,Fruits,Online,L,5/7/2010,686048400,5/10/2010,5822,9.33,6.92,54319.26,40288.24,14031.02
26,Australia and Oceania,Kiribati,Fruits,Online,M,10/13/2014,347140347,11/10/2014,5398,9.33,6.92,50363.34,37354.16,13009.18
23,Australia and Oceania,New Zealand,Fruits,Online,H,9/8/2014,142278373,10/4/2014,2187,9.33,6.92,20404.71,15134.04,5270.67
71,Middle East and North Africa,Libya,Fruits,Online,L,8/14/2015,816200339,9/30/2015,673,9.33,6.92,6279.09,4657.16,1621.93
86,Sub-Saharan Africa,Sao Tome and Principe,Beverages,Offline,C,1/16/2011,180283772,1/21/2011,8829,47.45,31.79,418936.05,280673.91,138262.14
89,Europe,Slovenia,Beverages,Offline,C,10/23/2016,345718562,11/25/2016,4660,47.45,31.79,221117.00,148141.40,72975.60
91,Australia and Oceania,Australia,Beverages,Offline,H,7/7/2014,240470397,7/11/2014,9389,47.45,31.79,445508.05,298476.31,147031.74
72,Sub-Saharan Africa,Democratic Republic of the Congo,Beverages,Online,C,5/26/2011,585920464,7/15/2011,5741,47.45,31.79,272410.45,182506.39,89904.06
17,Sub-Saharan Africa,Cameroon,Beverages,Offline,C,4/1/2015,519820964,4/18/2015,5430,47.45,31.79,257653.50,172619.70,85033.80
76,Australia and Oceania,Federated States of Micronesia,Beverages,Online,C,10/28/2014,217221009,11/15/2014,9379,47.45,31.79,445033.55,298158.41,146875.14
28,Europe,Norway,Beverages,Offline,C,7/18/2014,435608613,7/30/2014,5124,47.45,31.79,243133.80,162891.96,80241.84
94,Central America and the Caribbean,Nicaragua,Beverages,Offline,C,2/8/2011,963392674,3/21/2011,8156,47.45,31.79,387002.20,259279.24,127722.96
15,Europe,Bulgaria,Clothes,Online,M,4/23/2012,972292029,6/3/2012,1673,109.28,35.84,182825.44,59960.32,122865.12
55,Sub-Saharan Africa,Cote d'Ivoire,Clothes,Online,C,6/8/2012,114606559,6/27/2012,3482,109.28,35.84,380512.96,124794.88,255718.08
12,Asia,Bangladesh,Clothes,Online,L,1/13/2017,187310731,3/1/2017,8263,109.28,35.84,902980.64,296145.92,606834.72
81,Middle East and North Africa,Lebanon,Clothes,Online,L,9/18/2012,663110148,10/8/2012,7884,109.28,35.84,861563.52,282562.56,579000.96
95,Sub-Saharan Africa,Mali,Clothes,Online,M,7/26/2011,512878119,9/3/2011,888,109.28,35.84,97040.64,31825.92,65214.72
11,Sub-Saharan Africa,Cape Verde,Clothes,Offline,H,8/2/2014,939825713,8/19/2014,4168,109.28,35.84,455479.04,149381.12,306097.92
50,Europe,Albania,Clothes,Online,C,2/2/2010,385383069,3/18/2010,2269,109.28,35.84,247956.32,81320.96,166635.36
69,Sub-Saharan Africa,Madagascar,Clothes,Offline,L,4/25/2015,610425555,5/28/2015,7342,109.28,35.84,802333.76,263137.28,539196.48
63,Middle East and North Africa,Libya,Clothes,Offline,H,10/30/2010,705784308,11/17/2010,6116,109.28,35.84,668356.48,219197.44,449159.04
48,Europe,Macedonia,Clothes,Offline,C,10/14/2014,787399423,11/14/2014,7842,109.28,35.84,856973.76,281057.28,575916.48
56,Australia and Oceania,Fiji,Clothes,Offline,C,6/30/2010,647876489,8/1/2010,9905,109.28,35.84,1082418.40,354995.20,727423.20
67,Central America and the Caribbean,Belize,Clothes,Offline,M,7/25/2016,807025039,9/7/2016,5498,109.28,35.84,600821.44,197048.32,403773.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,Europe,Switzerland,Cosmetics,Offline,M,9/17/2012,249693334,10/20/2012,8661,437.20,263.33,3786589.20,2280701.13,1505888.07
65,Sub-Saharan Africa,Rwanda,Cosmetics,Offline,H,10/11/2013,699358165,11/25/2013,4477,437.20,263.33,1957344.40,1178928.41,778415.99
64,Central America and the Caribbean,Haiti,Cosmetics,Offline,H,10/13/2013,505716836,11/16/2013,1705,437.20,263.33,745426.00,448977.65,296448.35
41,Middle East and North Africa,Azerbaijan,Cosmetics,Online,M,2/6/2010,382392299,2/25/2010,7234,437.20,263.33,3162704.80,1904929.22,1257775.58
46,Europe,Iceland,Cosmetics,Online,C,12/31/2016,331438481,12/31/2016,8867,437.20,263.33,3876652.40,2334947.11,1541705.29
82,Middle East and North Africa,Iran,Cosmetics,Online,H,11/15/2016,286959302,12/8/2016,6489,437.20,263.33,2836990.80,1708748.37,1128242.43
79,Australia and Oceania,Samoa,Cosmetics,Online,H,7/20/2013,670854651,8/7/2013,9654,437.20,263.33,4220728.80,2542187.82,1678540.98
37,Sub-Saharan Africa,The Gambia,Meat,Online,M,1/14/2017,825304400,1/23/2017,4767,421.89,364.69,2011149.63,1738477.23,272672.40
19,Australia and Oceania,East Timor,Meat,Online,L,7/31/2012,322067916,9/11/2012,5908,421.89,364.69,2492526.12,2154588.52,337937.60
80,Europe,Spain,Household,Offline,L,10/21/2012,213487374,11/30/2012,4513,668.27,502.54,3015902.51,2267963.02,747939.49
99,Sub-Saharan Africa,Mozambique,Household,Offline,L,2/10/2012,665095412,2/15/2012,5367,668.27,502.54,3586605.09,2697132.18,889472.91
58,Europe,United Kingdom,Household,Online,L,1/5/2012,955357205,2/14/2012,282,668.27,502.54,188452.14,141716.28,46735.86
6,Sub-Saharan Africa,Angola,Household,Offline,M,4/23/2011,135425221,4/27/2011,4187,668.27,502.54,2798046.49,2104134.98,693911.51
13,Central America and the Caribbean,Honduras,Household,Offline,H,2/8/2017,522840487,2/13/2017,8974,668.27,502.54,5997054.98,4509793.96,1487261.02
18,Asia,Turkmenistan,Household,Offline,L,12/30/2010,441619336,1/20/2011,3830,668.27,502.54,2559474.10,1924728.20,634745.90
33,Asia,Myanmar,Household,Offline,H,1/16/2015,177713572,3/1/2015,8250,668.27,502.54,5513227.50,4145955.00,1367272.50
75,North America,Mexico,Household,Offline,C,11/6/2014,986435210,12/12/2014,6954,668.27,502.54,4647149.58,3494663.16,1152486.42
29,Sub-Saharan Africa,The Gambia,Household,Offline,L,5/26/2012,886494815,6/9/2012,2370,668.27,502.54,1583799.90,1191019.80,392780.10
70,Asia,Turkmenistan,Office Supplies,Online,M,4/23/2013,462405812,5/20/2013,5010,651.21,524.96,3262562.10,2630049.60,632512.50
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157,5/8/2014,1779,651.21,524.96,1158502.59,933903.84,224598.75
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712,2/6/2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50
92,Middle East and North Africa,Azerbaijan,Office Supplies,Online,M,6/13/2012,423331391,7/24/2012,2021,651.21,524.96,1316095.41,1060944.16,255151.25
90,Sub-Saharan Africa,Sierra Leone,Office Supplies,Offline,H,12/6/2016,621386563,12/14/2016,948,651.21,524.96,617347.08,497662.08,119685.00
38,Asia,Brunei,Office Supplies,Online,L,4/1/2012,320009267,5/8/2012,6708,651.21,524.96,4368316.68,3521431.68,846885.00
39,Europe,Bulgaria,Office Supplies,Online,M,2/16/2012,189965903,2/28/2012,3987,651.21,524.96,2596374.27,2093015.52,503358.75
53,Sub-Saharan Africa,Sierra Leone,Office Supplies,Offline,M,11/26/2011,441888415,1/7/2012,3457,651.21,524.96,2251232.97,1814786.72,436446.25
62,Sub-Saharan Africa,Cameroon,Office Supplies,Online,M,11/7/2011,177636754,11/15/2011,5518,651.21,524.96,3593376.78,2896729.28,696647.50
68,Europe,Lithuania,Office Supplies,Offline,H,10/24/2010,166460740,11/17/2010,8287,651.21,524.96,5396577.27,4350343.52,1046233.75
32,Australia and Oceania,Australia,Office Supplies,Online,C,10/27/2015,158535134,11/25/2015,2924,651.21,524.96,1904138.04,1534983.04,369155.00
49,Sub-Saharan Africa,Mauritania,Office Supplies,Offline,C,1/11/2012,837559306,1/13/2012,1266,651.21,524.96,824431.86,664599.36,159832.50

This tutorial only scratches the surface of what Pandas can do! There's so much more to take advantage of when the need arises. 

Some other potentially useful functions include:
1. Functions like median, mean, min, max, sum also exist in pandas. Does a good job of supporting missing values.
2. map/ apply/ applymap 
3. Whole lot more!